name: Coveralls Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-cover:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Print Node.js version
        run: node -v
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Clear pnpm and npm cache
        run: pnpm store prune && npm cache clean --force
      - name: Install dependencies
        run: pnpm install
      - name: Set NODE_OPTIONS
        run: echo "NODE_OPTIONS=--experimental-modules" >> $GITHUB_ENV
      - name: Run tests and generate coverage
        run: npx vitest run --coverage
      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pnpm add coveralls --save-dev
          cat ./coverage/lcov.info | pnpm exec coveralls
